### ISSUE TITLE
Insert local images

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#96]
It should be possible to reuse images from a local media repository with the image tile. Now (with 1.0a3) it is only possible to upload new images.

**Comment by datakurre** [comment]
It would be easy to add, but how to make the image tile form easy with all the options? How should the image tile look like? (And of course it should be possible to just drag and drop images. Editor has already deco-old code for that, but nobody has looked into it yet). 

Tom Gross kirjoitti pe kesäkuuta 12 20:11:05 2015 GMT+0300:

**Comment by datakurre** [comment]
This is also related to https://github.com/plone/plone.app.mosaic/issues/98, because image tile schema should be refactored to be easier to understand (especially, after it's possible to both upload a new image or re-use existing image [using UUIDs, similarly as in external content]).

**Comment by djay** [comment]
Are we really still using the "media repository" idea? I don't think it's really needed and it's too big a change to Plone. 
Just create images inside the current page if it's folderish or in parent if not, or if there is only one place an image can be created in a site (via restrictions) then just show that. If the user wants to call that their media repository then they can.

**Comment by datakurre** [comment]
@djay Not anymore. We are using "persistent tiles" for images, with plone.app.drafts to cleanup the added images if edit is cancelled.

**Comment by datakurre** [comment]
Should "traditional images" be allowed in text tiles? (As in upload and linking via TinyMCE?) I've hope not. It would get confusing with too many ways to add images.

**Comment by djay** [comment]
No, as in creating an image content object. Doesn’t have to be inserted via the tinymce but I don’t think it’s a good idea to preclude it. What about inline images?
I’m not sure what a persistent tile gains us? What happens with videos? With SVG or some other kind of object? 
Dealing with images being deleted in the case where the page is deleted can also be handled with folderish pages.

**Comment by datakurre** [comment]
Drafted persistent tile works also on Add form. Videos and other possible image types would be the same (either with a custom tile or with enhanced image -> media tile). Although, for videos, OEmbedding from some video service makes more sense.

Inline images are an issue. Currently image can be made "inline" top left or top right of a text tile with float tile styles, but that has a few usability issues.
 
Inline TinyMCE toolbar with ploneimage plugin and folderish page would work if add form doesn't matter. A new tiny plugin, which would create image tiles instead of content image would be another option (and image tile could then be replaced with text tile with image).

**Comment by tomgross** [comment]
@djay Why is a media repository a big change to Plone? It is supported OOTB. Make a folder and put all images in it. You can even let the system do it with a contentrule.

**Comment by datakurre** [comment]
@tomgross There was a Deco related project plone.app.mediarepository, which enabled multi-file upload for selected folders and had nice image picker with previews.

**Comment by djay** [comment]
Yes that is what I'm saying. It is supported out of the box via folders and
image objects.
For context the original deco idea had the concept of getting rid of image
and media content types in plone completely. And instead forcing everyone
to store their media in a single special object per plone instance.
However that is not what mosaic is doing so ignore that.
Instead it is also doing something else which is a big change. Its storing
all media as an annotation on the object.  Which also has big functional
changes. No workflow is possible on images should you want it. No
permissions. No sharing of media between pages. Or at least not without
some kind of tile that can alias tiles from other pages (which would then
need a whole lot of other precautions to ensure someone modifying that page
doesn't end up breaking or changing more pages by mistake)
So this idea of moving images out of the plone virtual filesystem and
making them attributes if a page is not a small step. It has other
implications.
Perhaps a smaller step is just to keep image objects, make pages folderish
and solve the problem of adding subobjects inside the add form?

**Comment by datakurre** [comment]
I see this as an improvement for our editors, but it could be optional, so that there would be no image tiles, but only normal ploneimage-linking in TinyMCE.

You need to be somewhat technical to be able to think about where to upload images and how to reuse them. Most of our editors simply upload images to the default TinyMCE upload location and don't reuse much. Some want workflows to keep images private, but then fail to publish them when required. They see images as part of the document and don't like how they have to manage them separately.

Reusing images makes sense for translations and that should be taken care of when p.a.m. support for Mosaic is fixed.

> Dylan Jay <notifications@github.com> kirjoitti 26.6.2015 kello 4.46:
> 
> Yes that is what I'm saying. It is supported out of the box via folders and
> image objects.
> For context the original deco idea had the concept of getting rid of image
> and media content types in plone completely. And instead forcing everyone
> to store their media in a single special object per plone instance.
> However that is not what mosaic is doing so ignore that.
> Instead it is also doing something else which is a big change. Its storing
> all media as an annotation on the object. Which also has big functional
> changes. No workflow is possible on images should you want it. No
> permissions. No sharing of media between pages. Or at least not without
> some kind of tile that can alias tiles from other pages (which would then
> need a whole lot of other precautions to ensure someone modifying that page
> doesn't end up breaking or changing more pages by mistake)
> So this idea of moving images out of the plone virtual filesystem and
> making them attributes if a page is not a small step. It has other
> implications.
> Perhaps a smaller step is just to keep image objects, make pages folderish
> and solve the problem of adding subobjects inside the add form?
>

**Comment by djay** [comment]
> On 26 Jun 2015, at 1:08 pm, Asko Soukka <notifications@github.com> wrote:
> 
> I see this as an improvement for our editors, but it could be optional, so that there would be no image tiles, but only normal ploneimage-linking in TinyMCE.

I wasn’t suggesting only inserting image via tinymce. That would be a bad idea. I was suggesting that the image tile still exists but it also stores its images in Image objects.

I’m not saying we use persistent image tiles, I’m just saying we shouldn’t rush into it and should evaluate all options. Even more so when persistent tile images will result in lost functionality.
I think making it optional is a bad idea however. That just makes it more confusing. We need one good way of doing things (and the fact News in Plone uses images differently from Pages is a good example of what we shouldn’t repeat).

> 
> You need to be somewhat technical to be able to think about where to upload images and how to reuse them. Most of our editors simply upload images to the default TinyMCE upload location and don't reuse much. Some want workflows to keep images private, but then fail to publish them when required. They see images as part of the document and don’t like how they have to manage them separately.

yes you are right. These are all problems with Images as separate objects. We need to weigh up the fixes for those vs switching to storing images inside a page.But there are fixes:
- “they don’t want to manage images separately": 
   - that can be improved by using folderish pages so the default location is inside a page. Deleting a page then deletes the images
- “there is confusion when users forget to publish images along with a page": 
   - We have this issue regardless with File objects and anything linked to a page. We could solve this doing checks during publishing that warn about this. Possibly even a tick box to publish all associated content of a page such as linked pages, folders, images and files.Publishing should display an overlay that outlines the state of all related content.


> 
> Reusing images makes sense for translations and that should be taken care of when p.a.m. support for Mosaic is fixed.

**Comment by datakurre** [comment]
I still think that the gained simplicity of embedded images is worth of the lost functionality of making all images re-usable.  I want it, but if it should enabled by default, can be discussed.

That said, @bloodbare had some implementation for imagetiles, and I recall that resulting real image content.

> Dylan Jay <notifications@github.com> kirjoitti 26.6.2015 kello 9.25:- “they don’t want to manage images separately": 
> - that can be improved by using folderish pages so the default location is inside a page. Deleting a page then deletes the images

This is not true when you are on Add form and our editors complained why they had to first create a page, save it, and only then they were able to edit it and upload images under it. We had to create a custom add script, which opens directly the edit form, but that has the old issue of filling the working area with unfinished abandoned content. 

I don't see us getting rid of add forms any time soon.

> - “there is confusion when users forget to publish images along with a page": 
> - We have this issue regardless with File objects and anything linked to a page. We could solve this doing checks during publishing that warn about this. Possibly even a tick box to publish all associated content of a page such as linked pages, folders, images and files.Publishing should display an overlay that outlines the state of all related content.

There's alread "attachment tile" for attaching files into document.

**Comment by hvelarde** [comment]
> This is not true when you are on Add form and our editors complained why they had to first create a page, save it, and only then they were able to edit it and upload images under it…

I have the same request with our customers, I barely remember there's a widget somewhere that handles this.

**Comment by datakurre** [comment]
This has now been fixed in current master and upcoming 2.0 (for Plone 5) with a few changes:

* Mosaic editor is no longer enabled on add form, but add form is replaced with a simple form with only title and description

* Separate image tile has been deprecated and is no longer available by default, but images must be inserted and uploaded into rich text tiles (as with normal TinyMCE based rich text fields)
